import type { WorkflowStage } from "../contracts/artifact.js";
import type { GenerateArtifactInput } from "./types.js";
import {
  bulletList,
  formatContextFiles,
  formatHumanNotes,
  formatPreviousArtifacts,
  formatTask,
  numberedList,
} from "./markdown-helpers.js";

type StageRenderer = (input: GenerateArtifactInput) => string;

const stageRenderers: Record<WorkflowStage, StageRenderer> = {
  requirement_orientation: renderRequirementOrientation,
  system_modeling: renderSystemModeling,
  technical_design: renderTechnicalDesign,
  coding_plan: renderCodingPlan,
  verification: renderVerification,
  debug: renderDebug,
  asset_feedback: renderAssetFeedback,
};

export function renderArtifactMarkdown(input: GenerateArtifactInput): string {
  return `${stageRenderers[input.stage](input).trim()}\n`;
}

function renderRequirementOrientation(input: GenerateArtifactInput): string {
  return [
    "# 需求定向",
    "",
    "## 本期目标",
    formatTask(input),
    "- 明确本期研发任务要解决的发布链路问题，并形成后续阶段可复用的范围边界。",
    "",
    "## 做什么",
    "- 从 PRD、评审记录、技术方案和 domain context 中提取本期要覆盖的产品链路。",
    "- 区分多个应用模块的差异点、共性路径和配置快照发布的复用机会。",
    "- 输出后续现状建模、技术方案、coding plan 和验证闭环需要使用的问题清单。",
    "",
    "## 不做什么",
    "- 不在本阶段直接修改产品代码或做完整自动化 agent 编排。",
    "- 不把尚未回到代码、日志或配置确认的假设写成确定结论。",
    "- 不扩展复杂 UI、eval dashboard 或真实外部 LLM 调用。",
    "",
    "## 关键产品问题",
    "- 哪些应用模块需要发布配置快照，哪些只需要透传或校验配置结果？",
    "- 多应用模块是否共享同一发布入口、同一数据模型和同一幂等策略？",
    "- 配置快照失败、超时或下游不可用时，产品侧应该降级、重试还是阻断发布？",
    "- 输入 context：",
    formatContextFiles(input.contextFiles),
    "",
    "## 待确认问题",
    "- 当前需求是否只覆盖配置快照发布，还是也包含配置快照生成、回填和校验？",
    "- 不同应用模块的发布链路差异是否来自产品规则、配置模型还是下游 RPC 能力？",
    "- smoke case 需要覆盖哪些模块、租户、配置类型和异常分支？",
    "",
    "## 人工确认点",
    formatHumanNotes(input.humanNotes),
  ].join("\n");
}

function renderSystemModeling(input: GenerateArtifactInput): string {
  return [
    "# 现状建模",
    "",
    "## 当前链路",
    formatTask(input),
    "- 从页面或上游任务进入应用模块发布接口后，发布服务会读取配置参数、配置上下文和模块类型。",
    "- 配置快照发布链路应区分配置主数据发布、配置快照发布、下游 RPC 写入和异步补偿。",
    "- 前序 artifact：",
    formatPreviousArtifacts(input.previousArtifacts),
    "",
    "## 关键入口",
    "- 发布入口：应用模块发布 API、配置发布 service、配置快照发布 helper。",
    "- 查询入口：配置详情、配置快照回显、校验结果或状态看板相关读取路径。",
    "- 失败入口：smoke case、日志 requestId、下游 RPC error、超时配置和测试租户权限。",
    "",
    "## 相关 repo / 模块",
    "- domain context：识别产品域链路、模块差异和上下游服务边界。",
    "- repo-code-map：定位 handler、service、model、RPC client 和发布落点。",
    "- repo-for-codegen：指导 coding 阶段优先阅读的文件和改动顺序。",
    "- repo-for-debug：指导验证失败时回到日志、配置、测试租户和下游 RPC。",
    "- 输入 context：",
    formatContextFiles(input.contextFiles),
    "",
    "## 上下游依赖",
    "- 上游：PRD、客户端提交参数、配置评估/校验结果、配置草稿。",
    "- 本服务：发布入口、配置模型转换、配置快照发布、幂等和事务边界。",
    "- 下游：配置快照服务、配置发布 RPC、配置中心、日志平台和效果回显链路。",
    "",
    "## 当前系统约束",
    "- 多模块发布链路可能存在字段粒度、入口复用和事务一致性差异。",
    "- 下游 RPC 超时、租户权限和测试数据状态会直接影响 smoke 结果。",
    "- 当前 MVP 只建模 artifact 生成，不自动读取真实仓库或调用外部平台。",
    "",
    "## 仍需回到代码确认的问题",
    bulletList(
      [
        "不同应用模块当前是否共用发布 handler 和 service。",
        "配置快照字段是随配置主数据一起落库，还是独立表 / 独立 RPC 写入。",
        "发布失败时现有代码是否已有重试、降级、事务回滚或补偿机制。",
        "日志中能否稳定关联 taskId、configId、moduleType 和下游 RPC requestId。",
      ],
      "暂无。",
    ),
    "",
    "人工 notes：",
    formatHumanNotes(input.humanNotes),
  ].join("\n");
}

function renderTechnicalDesign(input: GenerateArtifactInput): string {
  return [
    "# 技术方案",
    "",
    "## 背景",
    formatTask(input),
    "- 本任务需要在多个应用模块发布链路中统一配置快照发布口径，同时保留模块差异。",
    "- 方案必须能被 review、comment，并继续交给 agent 修改。",
    "",
    "## 目标",
    "- 明确配置快照发布的复用路径、模块差异和责任边界。",
    "- 形成对代码改动顺序、验证路径和失败收敛方式有直接指导意义的方案。",
    "- 保持 MVP 范围：只生成 Markdown artifact 和 trace，不引入 runtime 编排或真实 LLM 调用。",
    "",
    "## 方案概述",
    "- 以 workflow stage spec 作为阶段定义 source of truth。",
    "- 使用模板生成稳定 Markdown artifact，后续可替换为 LLM renderer。",
    "- 每次生成 artifact 同步产出 trace，记录 context、前序 artifact、人工 notes 和输出 id。",
    "",
    "## 详细设计",
    numberedList(
      [
        "合同层复用 Artifact contract，统一 stage、title、markdown 和 metadata。",
        "Stage spec 层定义 title、description、expectedInputs、expectedOutputs、humanCheckpoint 和 promptTemplate。",
        "Generator 层接收 task、stage、contextFiles、previousArtifacts 和 humanNotes，调用 renderer 生成 markdown。",
        "Trace 层为每个阶段记录输入摘要、contextUsed、previousArtifactsUsed、humanNotesUsed 和 outputArtifactId。",
        "Demo 层读取内置 demo context，按固定阶段顺序生成 7 个 Markdown 文件和 trace.json。",
      ],
      "暂无详细设计。",
    ),
    "",
    "## 影响面",
    "- 新增 TypeScript workflow 模块、demo script、内置 demo context、本地 demo 产物和 README。",
    "- 不修改无关代码，不引入重依赖，不接外部 LLM、真实仓库读取或复杂 UI。",
    "- 后续 Dorey 可直接加载本地生成的 demo Markdown 文件。",
    "",
    "## 风险与兼容性",
    "- 模板生成不会理解真实代码语义，必须通过人工 review 和后续 LLM 接入补强。",
    "- 如果后续 Artifact contract 扩展字段，需要保持当前最小字段向后兼容。",
    "- trace.json 是 demo 级聚合格式，后续 runtime 化前不承担状态机职责。",
    "",
    "## 验证方案",
    "- typecheck 确认 TypeScript contract、stage spec 和 generator API 可编译。",
    "- unit test 确认 7 个 stage、promptTemplate、Markdown heading、trace 和 demo 文件名稳定。",
    "- 运行 npm run generate:demo，检查本地 demo 产物可直接 review。",
    "",
    "## 人工决策点",
    formatHumanNotes(input.humanNotes),
    "",
    "参考 context：",
    formatContextFiles(input.contextFiles),
    "",
    "前序 artifact：",
    formatPreviousArtifacts(input.previousArtifacts),
  ].join("\n");
}

function renderCodingPlan(input: GenerateArtifactInput): string {
  return [
    "# Coding Plan",
    "",
    "## 执行原则",
    "- 保持 TypeScript 模块边界清晰：contract、stage spec、renderer、generator、demo data 分开。",
    "- 先用测试锁定 contract、stage spec、trace 和 demo 输出，再实现最小代码。",
    "- 不引入重依赖，不实现真实 agent runtime、状态机或外部 LLM 调用。",
    "",
    "## 涉及 repo",
    "- 当前 workspace：dorey。",
    "- 未来产品 repo：由 repo-code-map 和 repo-for-codegen context 指向，MVP 不自动读取。",
    "- 输入 context：",
    formatContextFiles(input.contextFiles),
    "",
    "## 改动步骤",
    numberedList(
      [
        "创建或复用 Artifact contract，保证 stage union 与工作流阶段一致。",
        "定义 WorkflowStageSpec，并为每个阶段补齐 promptTemplate。",
        "实现 template renderer 和 generateArtifact API，返回 Artifact 与 WorkflowTrace。",
        "实现 demo task builder 和 npm run generate:demo 脚本。",
        "补齐内置 demo context、README、本地 Markdown 产物和 trace.json。",
      ],
      "暂无改动步骤。",
    ),
    "",
    "## 文件级计划",
    "- src/contracts/artifact.ts：最小 Artifact contract 和 stage union。",
    "- src/workflow/stages.ts：stage specs 与 promptTemplate。",
    "- src/workflow/stage-renderers.ts：按阶段生成稳定 Markdown。",
    "- src/workflow/generator.ts：组装 artifact metadata 与 WorkflowTrace。",
    "- src/demo/demo-task.ts：demo task、context 读取、文件输出计划。",
    "- scripts/generate-demo-task.ts：一键生成 demo artifacts。",
    "- src/demo/demo-task.ts：内置 demo context 和任务描述。",
    "- generated/demo-task/*：本地忽略的 demo 输出。",
    "",
    "## Checkpoint",
    "- Checkpoint 1：typecheck 通过，stage spec 和 contract 类型稳定。",
    "- Checkpoint 2：unit test 通过，generator trace 和 demo file set 稳定。",
    "- Checkpoint 3：npm run generate:demo 产出 7 个 Markdown 和 trace.json。",
    "",
    "## 完成定义",
    "- 7 个阶段 Markdown 文件都存在，标题和二级 heading 与规范一致。",
    "- trace.json 记录每个阶段的 context、前序 artifact、人工 notes 和输出 artifact id。",
    "- README 说明生成命令、输出目录、workspace review 方法和后续 LLM / Codex agent 接入点。",
    "",
    "人工 notes：",
    formatHumanNotes(input.humanNotes),
    "",
    "前序 artifact：",
    formatPreviousArtifacts(input.previousArtifacts),
  ].join("\n");
}

function renderVerification(input: GenerateArtifactInput): string {
  return [
    "# 验证闭环",
    "",
    "## UT",
    "- 覆盖 stage union、WorkflowStageSpec 数量、promptTemplate 和 Markdown heading 稳定性。",
    "- 覆盖 generateArtifact 的 metadata、sourceRefs、trace 字段和人工 notes 透传。",
    "- 覆盖 demo builder 产出的 7 个 artifact 文件名和 trace entries 顺序。",
    "",
    "## Smoke",
    "- 运行 npm run generate:demo。",
    "- 检查本地 generated/demo-task 下存在 01 到 07 的 Markdown 文件和 trace.json。",
    "- 抽查 Markdown 是否能被 workspace 作为普通 artifact 加载、review 和 comment。",
    "",
    "## 联调",
    "- MVP 不接真实外部系统；联调范围是 demo artifacts 与 Dorey 的文件加载约定。",
    "- 后续接真实 agent 时，先把 generateArtifact 的 renderer 替换为 LLM-backed renderer，再保留 trace 输出。",
    "",
    "## 日志与证据",
    "- 构建证据：npm run typecheck。",
    "- 测试证据：npm test。",
    "- 产物证据：本地 generated/demo-task/trace.json 中每个 stage 的 inputSummary 和 outputArtifactId。",
    "- 输入 context：",
    formatContextFiles(input.contextFiles),
    "",
    "## 回归范围",
    "- Artifact contract 字段兼容性。",
    "- Stage heading 和文件命名稳定性。",
    "- Demo context 读取路径和 output directory 写入行为。",
    "",
    "## 验证通过标准",
    "- typecheck、test 和 generate:demo 全部成功。",
    "- 7 个 Markdown artifact 与 trace.json 均可在本地 generated/demo-task 中找到。",
    "- trace entries 的 contextUsed、previousArtifactsUsed 和 humanNotesUsed 与输入一致。",
    "",
    "人工 notes：",
    formatHumanNotes(input.humanNotes),
    "",
    "前序 artifact：",
    formatPreviousArtifacts(input.previousArtifacts),
  ].join("\n");
}

function renderDebug(input: GenerateArtifactInput): string {
  return [
    "# Debug 收敛",
    "",
    "## 失败现象",
    "- 若 npm run generate:demo 失败，先记录命令输出、退出码和缺失文件。",
    "- 若 smoke 失败，记录模块类型、测试租户、configId、requestId、下游 RPC 错误和超时配置。",
    "- 当前任务：",
    formatTask(input),
    "",
    "## 首查路径",
    numberedList(
      [
        "先看本地命令输出，确认是 typecheck、test、文件读取还是写入失败。",
        "再看 trace.json 是否缺少 contextUsed、previousArtifactsUsed 或 outputArtifactId。",
        "产品 smoke 失败时，先用 requestId 关联发布入口、配置快照发布和下游 RPC。",
        "检查测试租户权限、配置状态、配置中心超时和下游 mock / 真实环境差异。",
      ],
      "暂无首查路径。",
    ),
    "",
    "## 证据来源",
    "- 本地：npm test、npm run typecheck、npm run generate:demo、本地 generated/demo-task/trace.json。",
    "- 产品：日志平台、下游 RPC request/response、配置中心、测试租户和配置数据。",
    "- 输入 context：",
    formatContextFiles(input.contextFiles),
    "",
    "## 排查顺序",
    numberedList(
      [
        "确认失败是否可复现，并保留完整命令或 requestId。",
        "确认输入 context、前序 artifact 和 human notes 是否进入 trace。",
        "确认发布入口是否命中预期模块类型和配置模型。",
        "确认下游 RPC、配置和租户权限是否与 smoke case 匹配。",
        "修复后重新跑最小失败 case，再跑完整验证闭环。",
      ],
      "暂无排查顺序。",
    ),
    "",
    "## 可能根因",
    "- 模板或 stage spec heading 与 workspace 约定不一致。",
    "- demo context 路径不在当前 cwd 下，导致 contextUsed 为空或读取失败。",
    "- 产品 smoke 中下游 RPC 超时、测试租户无权限、mock 数据与真实链路不一致。",
    "- 发布逻辑只覆盖单一应用模块，未处理多模块差异字段。",
    "",
    "## 修复后验证",
    "- 本地修复后重新运行 typecheck、test 和 generate:demo。",
    "- 产品修复后用同一测试租户和配置参数复跑 smoke，并保留日志证据。",
    "- 如果根因改变需求边界，回写 requirement_orientation 或 technical_design artifact。",
    "",
    "人工 notes：",
    formatHumanNotes(input.humanNotes),
    "",
    "前序 artifact：",
    formatPreviousArtifacts(input.previousArtifacts),
  ].join("\n");
}

function renderAssetFeedback(input: GenerateArtifactInput): string {
  return [
    "# 资产回流",
    "",
    "## Context Patch 建议",
    "- 将多应用模块发布链路中的共用入口、差异字段和下游依赖补充到 domain context。",
    "- 将配置快照字段、幂等策略、事务边界和回显路径补充到 repo context。",
    "- 将验证失败时高信号证据来源补充到 repo-for-debug。",
    "- 输入 context：",
    formatContextFiles(input.contextFiles),
    "",
    "## Skill / Workflow Patch 建议",
    "- 在 workflow distillation 流程中保留阶段化 artifact、trace 和人工 checkpoint。",
    "- 对发布链路改造类任务，要求先完成 requirement_orientation 与 system_modeling，再进入 technical_design。",
    "- 对 smoke 失败类任务，要求 debug artifact 明确日志、配置、测试租户和下游 RPC 的排查顺序。",
    "",
    "## Eval Case 建议",
    "- 构造多应用模块共享发布入口但字段差异不同的 case，评估是否能输出正确 coding plan。",
    "- 构造下游 RPC 超时或测试租户无权限的 smoke 失败 case，评估 debug 收敛质量。",
    "- 构造需求边界不清的 PRD case，评估 requirement_orientation 是否能拆出待确认问题。",
    "",
    "## 不应沉淀的内容",
    "- 单次测试租户、一次性 requestId、临时 mock 地址和仅在当前环境成立的配置值。",
    "- 未经过代码、日志或 reviewer 确认的产品猜测。",
    "- 与配置快照发布无关的应用模块泛化结论。",
    "",
    "## 需要人工审核的内容",
    "- 是否把一次性故障错误地写成通用 debug 规则。",
    "- context patch 是否包含敏感业务细节或不可公开的环境信息。",
    "- skill / workflow patch 是否真的复用，还是只适合本次任务。",
    "- 前序 artifact：",
    formatPreviousArtifacts(input.previousArtifacts),
    "- 人工 notes：",
    formatHumanNotes(input.humanNotes),
  ].join("\n");
}
