import type { WorkflowStage } from "../contracts/artifact.js";

export const STAGE_MARKDOWN_SECTIONS: Record<WorkflowStage, readonly string[]> = {
  requirement_orientation: [
    "# 需求定向",
    "## 本期目标",
    "## 做什么",
    "## 不做什么",
    "## 关键产品问题",
    "## 待确认问题",
    "## 人工确认点",
  ],
  system_modeling: [
    "# 现状建模",
    "## 当前链路",
    "## 关键入口",
    "## 相关 repo / 模块",
    "## 上下游依赖",
    "## 当前系统约束",
    "## 仍需回到代码确认的问题",
  ],
  technical_design: [
    "# 技术方案",
    "## 背景",
    "## 目标",
    "## 方案概述",
    "## 详细设计",
    "## 影响面",
    "## 风险与兼容性",
    "## 验证方案",
    "## 人工决策点",
  ],
  coding_plan: [
    "# Coding Plan",
    "## 执行原则",
    "## 涉及 repo",
    "## 改动步骤",
    "## 文件级计划",
    "## Checkpoint",
    "## 完成定义",
  ],
  verification: [
    "# 验证闭环",
    "## UT",
    "## Smoke",
    "## 联调",
    "## 日志与证据",
    "## 回归范围",
    "## 验证通过标准",
  ],
  debug: [
    "# Debug 收敛",
    "## 失败现象",
    "## 首查路径",
    "## 证据来源",
    "## 排查顺序",
    "## 可能根因",
    "## 修复后验证",
  ],
  asset_feedback: [
    "# 资产回流",
    "## Context Patch 建议",
    "## Skill / Workflow Patch 建议",
    "## Eval Case 建议",
    "## 不应沉淀的内容",
    "## 需要人工审核的内容",
  ],
};
